#ifndef MOONBOARD_DEV_SERVER_FIRMWARE_VERSION_H
#define MOONBOARD_DEV_SERVER_FIRMWARE_VERSION_H

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "dev"
#endif

#ifndef FIRMWARE_BUILD_ENV
#define FIRMWARE_BUILD_ENV "unknown"
#endif

#endif
